# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'

#source 'https://github.com/CocoaPods/Specs.git'

target 'PZXSwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PZXSwiftProject
  post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
            end
        end
    end


use_frameworks!
	pod 'R.swift'
  	pod 'RxGesture'
  	pod 'RxCocoa'
	pod 'HandyJSON'
  	pod 'Alamofire'
  	pod 'IQKeyboardManagerSwift'
	pod 'MJRefresh'
  	pod 'SDWebImage'
  	pod 'SnapKit'
	pod 'JGProgressHUD'
  	pod 'TZImagePickerController'
	pod 'CYLTabBarController'
	pod 'NVActivityIndicatorView'
	pod 'QMUIKit'
	pod 'SwiftyJSON'	
	pod 'Kingfisher'
	pod 'SVProgressHUD'




end
